---
#https://docs.ansible.com/ansible/2.3/include_vars_module.html
- name: "Load a variable file based on the OS type, or a default if not found"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    -  "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - default.yml


- name: "Install system packages"
  package:
    name: '{{ system_packages }}'
    use: '{{ ansible_pkg_mgr }}'
    state: present

- name: "upgrade all packages"
  yum:
    name: '*'
    state: latest 

- name: "Add oscap tasks"
  include_tasks: oscap.yml


- name: "run STIG"
  shell: bash /usr/share/scap-security-guide/bash/rhel8-script-stig.sh
  register: stig

- debug: var=stig.stdout_lines  

# https://docs.ansible.com/ansible/latest/modules/debug_module.html
- debug:
    var: stig
    verbosity: 2

