---

- name: "Create reports directory if it does not exist"
  file:
    path: /vagrant/redhat/
    state: directory
    mode: '0755'


- name: "oscap tool"
  shell: oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_rht-ccp --results-arf arf.xml --report /vagrant/debian/report.html --oval-results /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
  
- name: "display all possible choices"
  shell: oscap info /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
  
