---
- name: "vg-compute-06" 
  gather_facts: true  
  hosts: "vg-compute-06"
  become: yes
  vars:
    stigparam: true
    pcidssparam: false
    hipaaparam: false
  roles:
    - common
    - complianceascode

- name: "vg-compute-13"
  gather_facts: true
  hosts: "vg-compute-13"
  become: yes
  vars:
    stigparam: true
    pcidssparam: false  
  roles:
    - common
    - complianceascode

- name: "vg-compute-14"
  gather_facts: true
  hosts: "vg-compute-14"
  become: yes
  vars:
    stigparam: true
    pcidssparam: false  
    hipaaparam: false
  roles:
    - common
    - complianceascode

- name: "vg-compute-15"
  gather_facts: true
  hosts: "vg-compute-15"
  become: yes
  vars:
    stigparam: false
    pcidssparam: true  
    hipaaparam: false
  roles:
    - common
    - complianceascode

- name: "vg-compute-16"
  gather_facts: true
  hosts: "vg-compute-16"
  become: yes
  vars:
    stigparam: false
    pcidssparam: false  
    hipaaparam: true
  roles:
    - common
    - complianceascode