---
- name: "Boot all hosts"
  gather_facts: true
  hosts:  all
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  pre_tasks:
  - name: "Setting hostname"
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common

# - name: "vg-compute-06" # traditional syntax
#   gather_facts: true  
#   hosts: "vg-compute-06"
#   become: yes
#   vars:
#     stigparam: false
#     stigpcidss: true
#   roles:
#     - complianceascode
 
- name: "vg-compute-06"
  gather_facts: true  
  hosts: "vg-compute-06"
  become: yes
  tasks:
    - include_role:
        name: complianceascode
      tags:
        - pcidss
 

- name: "Install compliance as code"
  gather_facts: true
  hosts: vg-compute-13   
  become: yes
  roles:
    - role: complianceascode 
      # tags: [ pcidss ]  
  # roles:
  #   - complianceascode
  # tags:
  #   - pcidss  